---
title: "Histórico das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("knitr_setup.R")
```

Abaixo o histórico de atividades realizadas em classe e atividades extra
classe aplicadas.

- **04/03**: Apresentação da disciplina.
- **09/03**: Conceitos de amostragem. [Slides](01_introducao_e_amostragem/01_Introducao_a_Estatistica_e_amostragem.pdf)
- **11/03**: Classificação de variáveis. Análise exploratória de dados. [Material](02_Analise_Exploratoria_de_Dados.html)
- **16/03**: Análise exploratória de dados: variáveis quantitativas
  discretas e contínuas. [Material](02_Analise_Exploratoria_de_Dados.html)
- **18/03**: Gráficos para variáveis quantitativas contínuas. [Material](02_Analise_Exploratoria_de_Dados.html)
- **23/03**: Sabatina 1
- **30/03**: Medidas resumo: medidas de tendência central.
  [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)
- **01/04**: Medidas resumo: medidas de variabilidade.
  [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)
- **06/04**: Medidas resumo: medidas de posição relativa.
  [Slides](03_Medidas_resumo/03_Medidas_resumo.pdf)
- **08/04**: Sabatina 2
- **13/04**: Probabilidade: experimentos, eventos e conjuntos.
  Definições clássica e frequentista.
  [Slides](04_Probabilidade/04_Probabilidade.pdf)

## Exercícios

- [Lista 1][]: amostragem e análise exploratória de dados. [Gabarito 1][].
- [Lista 2][]: Medidas resumo. [Gabarito 2][].
- [Lista 3][]: Probabilidade.

[Lista 1]: exercicios/01_Amostragem_e_Exploratoria.pdf
[Gabarito 1]: exercicios/01_Amostragem_e_Exploratoria_GABARITO.pdf
[Lista 2]: exercicios/03_Medidas_resumo.pdf
[Gabarito 2]: exercicios/03_Medidas_resumo_GABARITO.pdf
[Lista 3]: exercicios/04_Probabilidade.pdf

## Scripts R

Abaixo estão disponíveis os scripts do R que geraram os resultados
apresentados nos slides ou nas páginas da disciplina. Os scripts são
apenas ilustrativos e direcionados para aqueles que querem usar o R para
fazer as análises, portanto não são parte obrigatória da disciplina.

**Observação**: Os scripts são extraídos automaticamente do código-fonte
dos slides, portanto deve haver alguns comandos (principalmente no
início dos scripts) que não fazem parte das análises, servem apenas para
configurações de código. Sempre rode o código com o acompanhamento dos
slides ou páginas correspondentes.

- [Script 1][]: Amostragem
- [Script 2][]: Análise exploratória de dados
- [Script 3][]: Medidas resumo

[Script 1]: 01_introducao_e_amostragem/script_amostragem.R
[Script 2]: 02_Analise_Exploratoria_de_Dados.R
[Script 3]: 03_Medidas_resumo/03_Medidas_resumo.R
